# Generated by Django 5.0 on 2023-12-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0003_alter_comment_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="created",
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
