# Generated by Django 5.0 on 2023-12-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0004_post_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="updated",
        ),
        migrations.AlterField(
            model_name="comment",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
