# Generated by Django 5.0 on 2023-12-30 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0005_remove_comment_updated_alter_comment_created_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
