# Generated by Django 5.0 on 2023-12-30 14:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0006_delete_profile_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True, verbose_name="내용"
            ),
        ),
    ]
