# Generated by Django 5.0 on 2024-01-08 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0008_notice_qna"),
    ]

    operations = [
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "post_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="board.post",
                    ),
                ),
            ],
            bases=("board.post",),
        ),
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
