# Generated by Django 5.0 on 2024-01-08 13:16

import django.db.models.deletion
import pgvector.django
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lecture", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_time", models.DateTimeField(null=True)),
                ("bot_time", models.DateTimeField(null=True)),
                ("user_message", models.TextField()),
                ("bot_message", models.TextField()),
                ("user_message_embedded", pgvector.django.VectorField(dimensions=1536)),
                ("bot_message_embedded", pgvector.django.VectorField(dimensions=1536)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lecture.video"
                    ),
                ),
            ],
        ),
    ]
