# Generated by Django 5.0 on 2024-01-03 01:57

import django.db.models.deletion
import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lecture", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_message", models.TextField()),
                ("bot_message", models.TextField()),
                ("user_message_embedded", pgvector.django.VectorField(dimensions=1536)),
                ("bot_message_embedded", pgvector.django.VectorField(dimensions=1536)),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="lecture.lecture",
                    ),
                ),
            ],
        ),
    ]
