# Generated by Django 5.0 on 2024-01-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="bot_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="user_time",
            field=models.DateTimeField(null=True),
        ),
    ]
