# Generated by Django 5.0 on 2024-01-06 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_remove_message_video_userandvideorelation_and_more"),
        ("lecture", "0007_alter_video_lecture_enrollment_video_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="user_and_video",
        ),
        migrations.AddField(
            model_name="message",
            name="enrollment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="lecture.enrollment",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="UserAndVideoRelation",
        ),
    ]
