# Generated by Django 5.0 on 2024-01-08 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_remove_message_user_and_video_message_enrollment_and_more"),
        (
            "lecture",
            "0009_alter_enrollment_unique_together_remove_video_users_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="enrollment",
        ),
        migrations.AddField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="video",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="lecture.video",
            ),
            preserve_default=False,
        ),
    ]
