# Generated by Django 5.0 on 2024-01-04 14:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_auto_20231224_1659"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="organization",
        ),
    ]
