# Generated by Django 3.2.23 on 2023-12-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_lecture_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='thumbnail',
            field=models.ImageField(default='default_thumbnail.jpg', upload_to='images/'),
        ),
    ]
