# Generated by Django 3.2.23 on 2023-12-23 04:52

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_lecture_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='notes',
        ),
        migrations.AddField(
            model_name='lecture',
            name='chapter',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='lecture',
            name='grade',
            field=models.SmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='lecture',
            name='reamin_time',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='lecture',
            name='summary',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='lecture',
            name='visited',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
