# Generated by Django 5.0 on 2023-12-28 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_rename_grade_lecture_rating_and_more"),
        ("lecture", "__first__"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="video",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="lecture.video",
            ),
        ),
    ]
