# Generated by Django 5.0 on 2023-12-28 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_lecture_video"),
        ("lecture", "__first__"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="video",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lecture.video",
            ),
        ),
    ]
