# Generated by Django 5.0 on 2023-12-30 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_alter_lecture_video"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Lecture",
        ),
    ]
