# Generated by Django 5.0 on 2023-12-28 12:20

import config.asset_storage
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "file",
                    models.FileField(
                        null=True,
                        storage=config.asset_storage.MediaStorage(),
                        upload_to="videos/",
                        verbose_name="",
                    ),
                ),
            ],
        ),
    ]
