# Generated by Django 5.0 on 2023-12-28 11:16

import config.asset_storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lecture", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.FileField(
                null=True,
                storage=config.asset_storage.MediaStorage(),
                upload_to="videos/",
                verbose_name="",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
