# Generated by Django 3.2.23 on 2023-12-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='videofile',
            new_name='file',
        ),
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
