# Generated by Django 5.0 on 2024-01-04 06:17

import config.asset_storage
import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lecture", "0002_alter_video_file_alter_video_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=100)),
                ("subject", models.CharField(default="", max_length=10)),
                ("teacher", models.CharField(default="", max_length=10)),
                (
                    "thumbnail",
                    models.ImageField(
                        default="default_thumbnail.jpg",
                        storage=config.asset_storage.MediaStorage(),
                        upload_to="images/",
                    ),
                ),
                ("summary", models.TextField(default="")),
                ("student_count", models.IntegerField(default=0)),
                (
                    "rating",
                    models.SmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("remain_time", models.DurationField(default=datetime.timedelta)),
            ],
        ),
        migrations.AddField(
            model_name="video",
            name="lecture",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lecture.lecture",
            ),
        ),
    ]
