# Generated by Django 5.0 on 2024-01-04 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lecture", "0003_lecture_video_lecture"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="title_info",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="video",
            name="video_duration",
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
