# Generated by Django 5.0 on 2024-01-08 06:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "lecture",
            "0009_alter_enrollment_unique_together_remove_video_users_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together=set(),
        ),
    ]
