# Generated by Django 5.0 on 2024-01-08 07:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lecture", "0010_alter_enrollment_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="playback_duration",
        ),
    ]
